spring:
  application:
    name: discodeit
  datasource:
    url: ${RDS_URL}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  sql:
    init:
      mode: never

logging:
  level:
    root: INFO
    com.sprint.mission.discodeit: INFO
management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics"

discodeit:
  storage:
    type: ${STORAGE_TYPE}
    local:
      root-path: ${STORAGE_LOCAL_ROOT_PATH:.discodeit/storage}
    s3:
      access-key: ${AWS_CREDENTIALS_ACCESS_KEY}
      secret-key: ${AWS_CREDENTIALS_SECRET_KEY}
      region: ${AWS_REGION}
      bucket: ${AWS_S3_BUCKET}
      presigned-url-expiration: ${AWS_S3_PRESIGNED_URL_EXPIRATION:600}
